# HMDA Data Exploration

This notebook explores the 2024 HMDA dataset. The goal is to understand the
structure of the data, identify potential issues, and establish some 
baseline SQL queries.

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# set display options to show all rows in the output

pd.set_option('display.max_rows', None)

In [3]:
data_path = Path("../data/hmda_2024.csv")

df = pd.read_csv(data_path, low_memory=False)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (208881, 99)

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,...,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2024,549300LYRWPSYPK6S325,31084,CA,6037,6.037536e+09,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,...,6.0,NaN,NaN,6481,98.64,98200,71,838,1320,72
1,2024,549300LYRWPSYPK6S325,31084,CA,6037,6.037911e+09,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,5142,36.66,98200,154,1563,1961,36
2,2024,549300LYRWPSYPK6S325,31084,CA,6037,6.037109e+09,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,3120,72.85,98200,125,823,985,64
3,2024,549300LYRWPSYPK6S325,31084,CA,6037,6.037901e+09,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,...,NaN,NaN,NaN,5626,69.36,98200,98,1036,1507,61
4,2024,549300LYRWPSYPK6S325,31084,CA,6037,6.037404e+09,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,6346,79.70,98200,94,1134,1488,46

In [4]:
# see column types

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 208881 entries, 0 to 208880
Data columns (total 99 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   activity_year                             208881 non-null  int64
 1   lei                                       208881 non-null  str
 2   derived_msa-md                            208881 non-null  int64
 3   state_code                                208820 non-null  str
 4   county_code                               208881 non-null  int64
 5   census_tract                              208395 non-null  float64
 6   conforming_loan_limit                     206427 non-null  str
 7   derived_loan_product_type                 208881 non-null  str
 8   derived_dwelling_category                 208881 non-null  str
 9   derived_ethnicity                         208881 non-null  str
 10  derived_race                              208881 non-null  str
 11  derived_sex                               208881 non-null  str
 12  action_taken                              208881 non-null  int64
 13  purchaser_type                            208881 non-null  int64
 14  preapproval                               208881 non-null  int64
 15  loan_type                                 208881 non-null  int64
 16  loan_purpose                              208881 non-null  int64
 17  lien_status                               208881 non-null  int64
 18  reverse_mortgage                          208881 non-null  int64
 19  open-end_line_of_credit                   208881 non-null  int64
 20  business_or_commercial_purpose            208881 non-null  int64
 21  loan_amount                               208881 non-null  float64
 22  loan_to_value_ratio                       140415 non-null  str
 23  interest_rate                             126804 non-null  str
 24  rate_spread                               92679 non-null   str
 25  hoepa_status                              208881 non-null  int64
 26  total_loan_costs                          79916 non-null   str
 27  total_points_and_fees                     4995 non-null    str
 28  origination_charges                       81959 non-null   str
 29  discount_points                           36818 non-null   str
 30  lender_credits                            31979 non-null   str
 31  loan_term                                 203724 non-null  str
 32  prepayment_penalty_term                   11760 non-null   str
 33  intro_rate_period                         57502 non-null   str
 34  negative_amortization                     208881 non-null  int64
 35  interest_only_payment                     208881 non-null  int64
 36  balloon_payment                           208881 non-null  int64
 37  other_nonamortizing_features              208881 non-null  int64
 38  property_value                            162237 non-null  str
 39  construction_method                       208881 non-null  int64
 40  occupancy_type                            208881 non-null  int64
 41  manufactured_home_secured_property_type   208881 non-null  int64
 42  manufactured_home_land_property_interest  208881 non-null  int64
 43  total_units                               208881 non-null  str
 44  multifamily_affordable_units              3332 non-null    str
 45  income                                    178649 non-null  float64
 46  debt_to_income_ratio                      131205 non-null  str
 47  applicant_credit_score_type               208881 non-null  int64
 48  co-applicant_credit_score_type            208881 non-null  int64
 49  applicant_ethnicity-1                     208738 non-null  float64
 50  applicant_ethnicity-2                     26550 non-null   float64
 51  applicant_ethnicity-3                     488 non-null     float64
 52  applicant_ethnicity-4                     9 non-null       float64
 53  applicant_ethnicity-5                     0 non-null       float64
 54  co-applicant_ethnicity-1                  208842 non-null  float64
 55  co-applicant_ethnicity-2                  11390 non-null   float64
 56  co-applicant_ethnicity-3                  163 non-null     float64
 57  co-applicant_ethnicity-4                  3 non-null       float64
 58  co-applicant_ethnicity-5                  0 non-null       float64
 59  applicant_ethnicity_observed              208881 non-null  int64
 60  co-applicant_ethnicity_observed           208881 non-null  int64
 61  applicant_race-1                          208736 non-null  float64
 62  applicant_race-2                          21312 non-null   float64
 63  applicant_race-3                          1387 non-null    float64
 64  applicant_race-4                          130 non-null     float64
 65  applicant_race-5                          27 non-null      float64
 66  co-applicant_race-1                       208826 non-null  float64
 67  co-applicant_race-2                       8832 non-null    float64
 68  co-applicant_race-3                       574 non-null     float64
 69  co-applicant_race-4                       59 non-null      float64
 70  co-applicant_race-5                       8 non-null       float64
 71  applicant_race_observed                   208881 non-null  int64
 72  co-applicant_race_observed                208881 non-null  int64
 73  applicant_sex                             208881 non-null  int64
 74  co-applicant_sex                          208881 non-null  int64
 75  applicant_sex_observed                    208881 non-null  int64
 76  co-applicant_sex_observed                 208881 non-null  int64
 77  applicant_age                             208881 non-null  str
 78  co-applicant_age                          208881 non-null  str
 79  applicant_age_above_62                    186217 non-null  str
 80  co-applicant_age_above_62                 75172 non-null   str
 81  submission_of_application                 208881 non-null  int64
 82  initially_payable_to_institution          208881 non-null  int64
 83  aus-1                                     208881 non-null  int64
 84  aus-2                                     12891 non-null   float64
 85  aus-3                                     4289 non-null    float64
 86  aus-4                                     1292 non-null    float64
 87  aus-5                                     1075 non-null    float64
 88  denial_reason-1                           208881 non-null  int64
 89  denial_reason-2                           7518 non-null    float64
 90  denial_reason-3                           1353 non-null    float64
 91  denial_reason-4                           201 non-null     float64
 92  tract_population                          208881 non-null  int64
 93  tract_minority_population_percent         208881 non-null  float64
 94  ffiec_msa_md_median_family_income         208881 non-null  int64
 95  tract_to_msa_income_percentage            208881 non-null  int64
 96  tract_owner_occupied_units                208881 non-null  int64
 97  tract_one_to_four_family_homes            208881 non-null  int64
 98  tract_median_age_of_housing_units         208881 non-null  int64
dtypes: float64(31), int64(41), str(27)
memory usage: 157.8 MB

In [5]:
# see basic stats for numeric columns

df.describe()

,activity_year,derived_msa-md,county_code,census_tract,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,...,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
count,208881.0,208881.000000,208881.000000,2.083950e+05,208881.000000,208881.000000,208881.000000,208881.000000,208881.000000,208881.000000,...,7518.000000,1353.000000,201.000000,208881.000000,208881.000000,208881.000000,208881.000000,208881.000000,208881.000000,208881.000000
mean,2024.0,31558.481911,6038.963491,6.039399e+09,2.544545,6.842068,1.981147,1.156869,11.702615,1.337752,...,4.766294,6.009608,7.905473,4596.750408,67.721942,99092.107947,126.267693,891.646267,1223.061312,50.753276
std,0.0,2247.049623,9.298694,9.215133e+06,1.726317,19.435969,0.136006,0.427605,14.051284,0.472945,...,2.658627,2.399901,2.026332,1482.911357,24.781887,4224.841411,57.452370,450.879124,517.764168,18.453590
min,2024.0,31084.000000,6037.000000,6.037101e+09,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,98200.000000,0.000000,0.000000,0.000000,0.000000
25%,2024.0,31084.000000,6037.000000,6.037236e+09,1.000000,0.000000,2.000000,1.000000,1.000000,1.000000,...,3.000000,4.000000,7.000000,3545.000000,46.570000,98200.000000,85.000000,554.000000,858.000000,43.000000
50%,2024.0,31084.000000,6037.000000,6.037462e+09,2.000000,0.000000,2.000000,1.000000,2.000000,1.000000,...,4.000000,6.000000,9.000000,4455.000000,72.380000,98200.000000,116.000000,853.000000,1203.000000,55.000000
75%,2024.0,31084.000000,6037.000000,6.037604e+09,4.000000,2.000000,2.000000,1.000000,31.000000,2.000000,...,6.000000,9.000000,9.000000,5561.000000,90.700000,98200.000000,156.000000,1184.000000,1561.000000,63.000000
max,2024.0,42200.000000,6083.000000,6.083003e+09,8.000000,72.000000,2.000000,4.000000,32.000000,2.000000,...,9.000000,9.000000,9.000000,11373.000000,99.700000,119100.000000,311.000000,2223.000000,2993.000000,80.000000

In [6]:
# see proportion of missing values for each column

missing = df.isna().mean().sort_values(ascending=True)
display(missing)

activity_year                               0.000000
balloon_payment                             0.000000
other_nonamortizing_features                0.000000
construction_method                         0.000000
occupancy_type                              0.000000
manufactured_home_secured_property_type     0.000000
manufactured_home_land_property_interest    0.000000
total_units                                 0.000000
applicant_credit_score_type                 0.000000
co-applicant_credit_score_type              0.000000
tract_one_to_four_family_homes              0.000000
applicant_ethnicity_observed                0.000000
co-applicant_ethnicity_observed             0.000000
applicant_race_observed                     0.000000
co-applicant_race_observed                  0.000000
applicant_sex                               0.000000
co-applicant_sex                            0.000000
applicant_sex_observed                      0.000000
co-applicant_sex_observed                   0.000000
applicant_age                               0.000000
co-applicant_age                            0.000000
submission_of_application                   0.000000
initially_payable_to_institution            0.000000
aus-1                                       0.000000
denial_reason-1                             0.000000
tract_population                            0.000000
tract_minority_population_percent           0.000000
ffiec_msa_md_median_family_income           0.000000
tract_to_msa_income_percentage              0.000000
tract_owner_occupied_units                  0.000000
interest_only_payment                       0.000000
negative_amortization                       0.000000
tract_median_age_of_housing_units           0.000000
lien_status                                 0.000000
derived_loan_product_type                   0.000000
loan_purpose                                0.000000
derived_ethnicity                           0.000000
business_or_commercial_purpose              0.000000
loan_amount                                 0.000000
derived_race                                0.000000
open-end_line_of_credit                     0.000000
reverse_mortgage                            0.000000
county_code                                 0.000000
derived_sex                                 0.000000
action_taken                                0.000000
hoepa_status                                0.000000
purchaser_type                              0.000000
preapproval                                 0.000000
derived_msa-md                              0.000000
lei                                         0.000000
loan_type                                   0.000000
derived_dwelling_category                   0.000000
co-applicant_ethnicity-1                    0.000187
co-applicant_race-1                         0.000263
state_code                                  0.000292
applicant_ethnicity-1                       0.000685
applicant_race-1                            0.000694
census_tract                                0.002327
conforming_loan_limit                       0.011748
loan_term                                   0.024689
applicant_age_above_62                      0.108502
income                                      0.144733
property_value                              0.223304
loan_to_value_ratio                         0.327775
debt_to_income_ratio                        0.371867
interest_rate                               0.392937
rate_spread                                 0.556307
origination_charges                         0.607628
total_loan_costs                            0.617409
co-applicant_age_above_62                   0.640120
intro_rate_period                           0.724714
discount_points                             0.823737
lender_credits                              0.846903
applicant_ethnicity-2                       0.872894
applicant_race-2                            0.897971
aus-2                                       0.938285
prepayment_penalty_term                     0.943700
co-applicant_ethnicity-2                    0.945471
co-applicant_race-2                         0.957718
denial_reason-2                             0.964008
total_points_and_fees                       0.976087
aus-3                                       0.979467
multifamily_affordable_units                0.984048
applicant_race-3                            0.993360
denial_reason-3                             0.993523
aus-4                                       0.993815
aus-5                                       0.994854
co-applicant_race-3                         0.997252
applicant_ethnicity-3                       0.997664
denial_reason-4                             0.999038
co-applicant_ethnicity-3                    0.999220
applicant_race-4                            0.999378
co-applicant_race-4                         0.999718
applicant_race-5                            0.999871
applicant_ethnicity-4                       0.999957
co-applicant_race-5                         0.999962
co-applicant_ethnicity-4                    0.999986
applicant_ethnicity-5                       1.000000
co-applicant_ethnicity-5                    1.000000
dtype: float64

In [7]:
# investigate potentially important columns

df["loan_type"].value_counts(dropna=False)

loan_type
1    181368
2     22288
3      5196
4        29
Name: count, dtype: int64

In [8]:
df["loan_amount"].describe()

count    2.088810e+05
mean     6.030081e+05
std      2.497585e+06
min      5.000000e+03
25%      1.550000e+05
50%      4.250000e+05
75%      7.150000e+05
max      4.380050e+08
Name: loan_amount, dtype: float64

In [9]:
# look into why max is so high

df.nlargest(10, "loan_amount")[["loan_amount", "loan_type", "loan_purpose", 
                                "business_or_commercial_purpose", 
                                "total_units"]]

,loan_amount,loan_type,loan_purpose,business_or_commercial_purpose,total_units
95757,438005000.0,1,31,1,>149
95766,400005000.0,1,31,1,>149
22631,344225000.0,1,32,1,50-99
22632,344225000.0,1,32,1,100-149
22633,344225000.0,1,32,1,100-149
154854,300005000.0,1,1,2,1
95773,203205000.0,1,31,1,>149
154881,200005000.0,1,1,2,1
9509,172565000.0,1,1,1,>149
150752,172315000.0,1,31,1,>149

In [10]:
print("Mean:", df["loan_amount"].mean())
print("Median:", df["loan_amount"].median())

Mean: 603008.1481800643
Median: 425000.0

loan_amount distribution: The mean loan amount is much higher than the median.
This is important when interpreting average loan amounts.

In [11]:
df["action_taken"].value_counts(dropna=False)

action_taken
1    99805
3    39848
4    29676
6    18527
5    12366
2     8118
8      439
7      102
Name: count, dtype: int64

In [12]:
df["denial_reason-1"].value_counts(dropna=False)

denial_reason-1
10      168123
1        15939
7         6177
3         5872
4         4989
9         3871
6         1654
5         1089
1111       965
2          199
8            3
Name: count, dtype: int64

In [13]:
df["denial_reason-2"].value_counts(dropna=False)

denial_reason-2
NaN    201363
9.0      1509
4.0      1397
3.0      1342
1.0      1151
6.0       818
5.0       726
7.0       355
2.0       216
8.0         4
Name: count, dtype: int64

In [14]:
# look at denial reason only for loans that were denied

denied = df[df["action_taken"] == 3]
denied["denial_reason-1"].value_counts(dropna=False)

denial_reason-1
1       15919
7        6123
3        5862
4        4986
9        3865
6        1652
5        1085
2         197
1111      156
8           3
Name: count, dtype: int64

In [15]:
denied["denial_reason-2"].value_counts(dropna=False)

denial_reason-2
NaN    32339
9.0     1507
4.0     1397
3.0     1340
1.0     1151
6.0      815
5.0      726
7.0      354
2.0      215
8.0        4
Name: count, dtype: int64

In [16]:
df["loan_purpose"].value_counts(dropna=False)

loan_purpose
1     82251
32    42611
4     29309
2     27721
31    26578
5       411
Name: count, dtype: int64

In [17]:
df["county_code"].value_counts(dropna=False)

county_code
6037    199965
6083      8916
Name: count, dtype: int64

In [18]:
df["interest_rate"].value_counts(dropna=False)

interest_rate
NaN         82077
6.625        6875
6.875        4922
6.125        4473
7.125        4181
6.375        3410
6.990        3368
6.500        3017
7.375        2994
7.625        2894
6.250        2451
6.99         2418
6.750        2208
5.875        2114
6.5          2076
7.500        1952
5.625        1752
7.000        1681
7.250        1674
5.750        1642
8.500        1582
6.25         1482
6.000        1309
7.875        1293
9.000        1223
6.75         1216
9.500        1203
Exempt       1128
5.99         1124
7.750        1119
7.490        1070
8.000        1046
5.75          997
9.250         988
7.5           978
5.990         970
8.250         949
8.750         947
8.990         862
6.490         849
7.25          808
6.999         733
8.125         711
8.875         711
7             702
6             662
7.990         644
8.375         622
5.500         604
9.875         589
5.375         570
9.750         557
8.625         543
7.49          537
10.000        526
9.375         515
5.250         507
5.5           487
9.125         472
9.625         472
10.500        457
5.999         451
9.990         445
10.250        415
6.624         381
5.25          351
7.75          337
7.99          337
10.750        336
8.75          334
9.75          327
9.050         323
9.5           316
8.5           315
6.49          302
10.375        293
9.25          285
5.125         280
10.875        280
8             268
14.990        266
10.125        264
9             250
7.240         246
10.25         246
8.25          245
10.5          245
7.999         245
9.550         243
8.490         224
10.75         223
6.740         219
10.625        218
6.62500       212
4.99          206
4.750         202
10            202
11.500        199
11.250        195
11.000        190
6.499         189
5.749         179
9.300         178
6.124         178
10.990        177
7.499         171
4.875         165
11.375        160
0.000         157
11.490        149
6.99000       144
6.50000       143
6.87500       143
6.240         139
6.12500       137
7.12500       137
6.249         136
11.125        133
1.000         130
11.750        128
9.05          128
8.240         127
11.25         126
11.5          124
4.990         121
1             121
7.124         120
7.624         116
7.62500       116
9.740         115
11            112
5.49          106
9.490         105
9.8           104
8.999         104
11.875        103
8.800         102
10.050        101
2.990         101
10.950         97
9.3            96
8.550          95
6.575          94
13.990         94
11.625         90
9.240          89
7.50000        87
11.990         86
8.740          85
11.75          85
6.37500        85
9.4            84
12.990         84
9.999          83
8.300          82
10.99          81
8.950          80
8.8            80
8.55           78
9.950          78
5.000          77
12.000         75
12.500         75
7.37500        75
7.00000        73
9.55           72
9.800          72
12.250         71
6.6            69
8.700          69
10.490         69
7.374          69
9.9            68
9.450          68
12.740         68
10.550         68
6.55           67
6.1            67
8.65           67
10.55          67
3.875          66
9.99           65
8.499          65
0              64
9.65           63
5.624          63
9.15           62
9.85           62
9.6            62
5              62
5.87500        62
6.15           60
8.9            60
10.45          60
4.75           59
12.240         59
6.749          59
9.95           58
6.874          58
4.625          56
10.4           55
8.4            55
14.500         55
10.05          54
6.65           53
10.600         53
14.490         53
6.3            52
9.45           52
10.15          52
6.05           51
8.45           51
9.850          51
10.740         51
6.00000        51
6.45           50
6.4            50
8.650          50
12.25          50
12.750         49
5.85           49
10.65          49
7.850          49
6.35           48
6.2            48
5.99000        48
8.6            47
5.8            47
7.950          47
8.900          47
7.65           46
10.49          46
7.9            46
9.690          46
7.95           46
10.1           45
7.24           45
8.99           45
5.7            45
7.25000        45
6.8            44
11.45          44
10.8           44
9.400          44
8.200          44
5.499          44
13.500         44
7.249          44
13.240         44
2.875          43
5.490          43
9.7            43
10.2           43
8.85           43
9.700          43
13.000         43
7.874          43
7.749          43
12             43
10.35          43
10.7           43
6.75000        43
9.35           42
10.6           42
5.65           42
9.1            42
9.350          42
9.600          42
8.95           42
8.7            42
11.240         42
6.95           41
11.05          41
9.2            41
2.75           41
10.450         41
2.625          40
10.9           40
10.3           40
4.999          40
10.100         40
10.240         40
5.62500        40
6.85           39
5.95           39
8.3            39
7.450          39
4.125          38
5.9            38
8.35           38
13.750         38
6.475          37
6.998          37
5.740          36
11.7           36
10.85          36
11.350         36
3.125          35
11.55          35
6.950          35
9.100          35
7.075          34
4.375          34
9.900          34
7.700          34
7.900          34
5.249          34
11.1           33
4.25           33
4.5            33
10.95          33
7.650          33
6.7            32
11.3           32
10.800         32
8.150          32
8.600          32
12.125         32
8.450          32
5.74           31
8.850          31
9.200          31
8.400          31
13.740         31
15.490         31
7.45           30
5.55           30
3.625          30
10.900         30
6.400          30
10.350         30
8.2            30
3.5            29
13.250         29
7.740          29
6.374          29
7.59           29
6.9            28
3.375          28
8.860          28
6.450          28
8.15           28
12.5           28
13.5           28
11.740         28
11.2           27
6.24           27
11.850         27
11.100         27
9.650          27
7.7            27
12.490         27
11.450         27
6.25000        27
12.875         26
6.525          26
11.4           26
5.998          26
12.75          26
9.575          26
8.525          26
6.599          26
10.850         25
5.874          25
4.500          24
7.575          24
10.700         24
10.650         24
8.124          24
11.600         24
5.45           24
11.85          23
5.6            23
8.05           23
7.600          23
13.75          23
10.150         23
14.740         23
6.562          23
11.6           22
7.8            22
12.375         22
9.110          22
8.249          22
6.600          22
11.950         22
14.250         22
11.720         22
8.675          22
5.4            22
3.250          21
11.15          21
13.05          21
5.2            21
7.2            21
8.49           21
6.700          21
7.55           21
9.675          21
14.25          21
8.624          21
11.220         21
8.275          21
10.26          21
5.50000        21
6.175          20
6.075          20
3.75           20
11.99          20
10.400         20
6.650          20
8.610          20
12.15          20
14             20
11.35          20
3.500          20
14.240         20
7.550          20
6.49000        20
4.250          19
7.05           19
6.74           19
6.33           19
10.300         19
12.625         19
8.350          19
10.200         19
8.374          19
13             19
13.3           19
11.95          19
9.925          19
9.499          19
9.525          19
8.925          19
13.490         19
10.970         19
9.24           19
2.900          19
5.240          18
7.35           18
5.96           18
3.25           18
3              18
14.000         18
2.5            18
14.5           18
7.3            18
6.100          18
9.775          18
9.025          18
10.56          18
7.79           18
6.975          17
13.6           17
12.3           17
6.38           17
6.66           17
4              17
11.300         17
7.800          17
5.950          17
6.550          17
5.825          17
5.900          17
8.050          17
11.9           17
13.2           17
9.425          17
13.625         17
9.075          17
9.175          17
11.050         17
8.425          17
11.200         17
8.825          17
9.325          17
8.775          17
9.86           17
7.1            16
8.1            16
6.89           16
13.125         16
2.25           16
12.95          16
13.25          16
6.300          16
6.350          16
13.600         16
13.875         16
6.225          15
12.35          15
12.1           15
11.8           15
12.85          15
7.29           15
6.78           15
6.68           15
10.865         15
9.150          15
13.4           15
7.6            15
10.425         15
9.06           15
5.3            15
12.06          15
6.325          14
7.025          14
11.65          14
5.975          14
6.64           14
5.83           14
8.100          14
6.620          14
2.375          14
13.65          14
12.45          14
13.15          14
9.275          14
11.550         14
12.100         14
11.470         14
4.490          13
6.775          13
5.675          13
11.49          13
12.550         13
11.400         13
9.360          13
11.150         13
3.99           13
14.750         13
11.800         13
7.400          13
7.775          13
10.775         13
5.1            13
6.425          12
6.56           12
6.54           12
6.52           12
6.47           12
5.92           12
5.63           12
7.325          12
7.930          12
9.610          12
7.050          12
5.925          12
12.4           12
12.8           12
10.175         12
5.800          12
3.750          12
8.749          12
8.575          12
11.700         12
7.200          12
8.025          12
7.34           12
9.49           12
14.125         12
9.81           12
5.75000        12
7.87500        12
6.725          11
6.825          11
7.525          11
6.87           11
6.43           11
6.76           11
5.98           11
6.18           11
7.4            11
5.48           11
6.16           11
6.800          11
6.580          11
6.899          11
5.550          11
12.55          11
12.05          11
9.975          11
13.375         11
5.700          11
6.050          11
12.350         11
3.000          11
10.675         11
13.300         11
8.349          11
8.075          11
5.699          11
10.88          11
9.56           11
10.38          11
9.687          11
10.120         11
5.37500        11
6.025          10
6.925          10
6.275          10
12.6           10
12.65          10
7.85           10
2.99           10
6.21           10
6.44           10
6.28           10
6.51           10
5.69           10
9.860          10
6.850          10
7.350          10
6.495          10
11.175         10
12.9           10
14.3           10
12.2           10
11.900         10
10.275         10
10.025         10
9.225          10
13.150         10
13.050         10
7.975          10
12.300         10
7.51           10
11.675         10
10.999         10
8.325          10
14.875         10
9.94           10
7.49000        10
8.12500        10
6.62400        10
6.937          10
13.9            9
5.24            9
6.94            9
6.79            9
6.58            9
5.93            9
5.94            9
7.19            9
6.900           9
7.790           9
9.090           9
8.590           9
10.110          9
10.610          9
7.690           9
6.790           9
6.980           9
14.375          9
13.1            9
14.15           9
12.7            9
9.825           9
9.615           9
8.865           9
8.690           9
13.100          9
5.575           9
8.975           9
10.525          9
9.66            9
9.19            9
4.000           9
5.35            9
5.15            9
7.475           8
6.675           8
6.39            8
6.53            8
6.32            8
6.37            8
6.48            8
6.61            8
6.41            8
7.300           8
7.123           8
8.360           8
7.880           8
5.980           8
6.690           8
7.15            8
7.100           8
6.590           8
10.075          8
11.025          8
5.275           8
6.890           8
5.775           8
8.874           8
10.720          8
12.600          8
12.950          8
9.475           8
6.120           8
6.437           8
7.470           8
7.675           8
11.525          8
8.175           8
8.725           8
11.66           8
11.275          8
16.25           8
9.940           8
10.630          8
5.25000         8
7.99000         8
3.990           8
2.250           7
7.425           7
6.865           7
5.615           7
6.67            7
6.13            7
6.23            7
6.86            7
6.42            7
6.59            7
6.96            7
6.03            7
6.81            7
5.73            7
6.08            7
5.82            7
6.981           7
6.123           7
6.720           7
8.070           7
6.530           7
6.150           7
6.885           7
11.425          7
13.8            7
13.55           7
14.6            7
6.630           7
10.655          7
11.650          7
6.200           7
7.925           7
12.220          7
7.825           7
7.599           7
7.099           7
7.080           7
6.995           7
7.440           7
7.324           7
6.099           7
7.520           7
12.99           7
9.36            7
10.06           7
7.040           7
7.330           7
10.16           7
10.7500         7
1.75            7
11.074          7
9.249           7
7.062           7
5.725           6
13.85           6
6.365           6
6.19            6
6.62            6
6.29            6
6.92            6
7.01            6
6.71            6
6.88            6
6.69            6
5.88            6
6.06            6
6.04            6
5.76            6
5.87            6
11.365          6
11.74           6
9.865           6
5.985           6
7.69            6
13.200          6
7.175           6
6.940           6
8.840           6
7.340           6
8.370           6
7.070           6
6.780           6
6.880           6
7.510           6
7.130           6
6.860           6
6.370           6
14.2            6
14.45           6
2.831           6
7.120           6
9.365           6
9.725           6
5.600           6
8.640           6
9.374           6
8.790           6
13.650          6
14.150          6
14.600          6
13.400          6
12.470          6
10.470          6
7.399           6
7.385           6
5.620           6
6.199           6
2.999           6
7.54            6
7.37            6
7.065           6
13.99           6
10.975          6
15              6
10.74           6
9.44            6
9.26            6
7.580           6
7.290           6
7.630           6
7.150           6
1.875           6
4.510000        6
2.750           5
7.33            5
7.68            5
5.225           5
5.865           5
6.34            5
6.57            5
6.72            5
6.77            5
7.12            5
5.68            5
5.71            5
6.12            5
6.09            5
5.51            5
6.595           5
6.997           5
10.825          5
9.830           5
7.890           5
6.115           5
7.745           5
5.995           5
6.260           5
9.590           5
10.090          5
11.610          5
7.310           5
11.360          5
9.510           5
7.540           5
9.390           5
9.190           5
6.010           5
5.850           5
6.460           5
6.105           5
6.680           5
5.960           5
6.220           5
5.650           5
6.340           5
14.4            5
13.45           5
13.95           5
14.7            5
14.75           5
14.55           5
11.630          5
10.325          5
7.190           5
9.115           5
9.749           5
9.140           5
13.550          5
13.900          5
15.600          5
6.090           5
12.050          5
6.470           5
6.312           5
6.623           5
6.063           5
5.374           5
6.248           5
6.745           5
6.190           5
5.124           5
5.599           5
4.749           5
7.370           5
7.44            5
7.87            5
7.04            5
11.825          5
7.165           5
10.595          5
10.745          5
3.999           5
10.225          5
7.224           5
11.995          5
11.775          5
9.39            5
9.43            5
10.08           5
7.180           5
7.020           5
6.635           5
6.770           5
2.125           5
7.75000         5
6.2500          5
5.325           5
7.562           5
7.275           4
6.11            4
3.7             4
6.17            4
6.84            4
8.53            4
7.14            4
7.11            4
6.73            4
6.83            4
6.31            4
5.58            4
4.8             4
6.07            4
11.615          4
7.122           4
8.74            4
7.565           4
5.860           4
9.340           4
10.340          4
10.590          4
10.360          4
7.090           4
8.320           4
9.540           4
8.730           4
8.440           4
7.060           4
6.095           4
5.970           4
6.14            4
7.280           4
10.9500         4
6.390           4
14.1            4
13.35           4
14.8            4
8.57            4
7.38            4
9.46            4
6.520           4
14.625          4
10.115          4
10.530          4
5.425           4
10.190          4
8.940           4
10.880          4
11.880          4
12.720          4
13.350          4
12.800          4
6.870           4
5.590           4
5.629           4
6.188           4
6.170           4
6.399           4
6.040           4
6.974           4
6.915           4
7.430           4
7.570           4
6.831           4
7.52            4
7.26            4
7.395           4
7.67            4
7.64            4
12.015          4
7.39            4
11.665          4
7.58            4
9.74            4
7.27            4
10.345          4
11.209          4
10.475          4
7.574           4
12.225          4
7.774           4
11.225          4
7.174           4
10.925          4
15.75           4
8.224           4
11.925          4
12.075          4
15.5            4
9.48            4
9.64            4
9.91            4
9.54            4
10.11           4
9.69            4
10.01           4
9.63            4
7.680           4
7.420           4
7.170           4
7.6250          4
13.700          4
7.760           4
5.840           4
6.563           4
10.66           4
9.16            4
7.92            4
9.870           4
5.12500         4
6.5000          4
7.1250          4
7.50            4
11.589          4
10.596          4
9.730           4
9.356           4
9.199           4
5.05            4
4.825           4
6.812           4
7.312           4
7.437           4
14.9            3
14.85           3
7.365           3
7.43            3
6.63            3
4.49            3
6.27            3
6.98            3
3.37            3
3.6             3
6.46            3
6.02            3
5.84            3
5.53            3
6.01            3
5.66            3
7.36            3
5.97            3
3.65            3
6.405           3
10.615          3
6.984           3
7.57            3
6.539           3
5.688           3
5.426           3
6.062           3
7.049           3
10.24           3
8.38            3
7.28            3
6.494           3
6.498           3
6.373           3
5.730           3
9.840           3
7.610           3
7.360           3
8.030           3
8.430           3
8.190           3
9.410           3
8.460           3
8.210           3
8.620           3
5.660           3
6.080           3
6.035           3
6.160           3
5.915           3
6.210           3
6.565           3
6.298           3
6.555           3

In [19]:
# why is interest_rate an object and not numeric?

interest_numeric = pd.to_numeric(df["interest_rate"], errors="coerce")

# how many additional missing values added after conversion?

print("Missing before:", df["interest_rate"].isna().sum())
print("Missing after:", interest_numeric.isna().sum())

df["interest_rate"][interest_numeric.isna() & df["interest_rate"].notna()]

Missing before: 82077
Missing after: 83205

9642      Exempt
9643      Exempt
9644      Exempt
9645      Exempt
13620     Exempt
13621     Exempt
14015     Exempt
14016     Exempt
14017     Exempt
14018     Exempt
14019     Exempt
14020     Exempt
14021     Exempt
14022     Exempt
14023     Exempt
14024     Exempt
14025     Exempt
14026     Exempt
14027     Exempt
14028     Exempt
14029     Exempt
14030     Exempt
14031     Exempt
14032     Exempt
14033     Exempt
14490     Exempt
14547     Exempt
14548     Exempt
14981     Exempt
28608     Exempt
28609     Exempt
28929     Exempt
28930     Exempt
28931     Exempt
28932     Exempt
28933     Exempt
28934     Exempt
28935     Exempt
28936     Exempt
28937     Exempt
28938     Exempt
28939     Exempt
28940     Exempt
29009     Exempt
29010     Exempt
29011     Exempt
29012     Exempt
29013     Exempt
29014     Exempt
29015     Exempt
29016     Exempt
29017     Exempt
29018     Exempt
29019     Exempt
29020     Exempt
29021     Exempt
29022     Exempt
29023     Exempt
29024     Exempt
29025     Exempt
29026     Exempt
29027     Exempt
29028     Exempt
29029     Exempt
29030     Exempt
29031     Exempt
29032     Exempt
29033     Exempt
29034     Exempt
29035     Exempt
29036     Exempt
29037     Exempt
29484     Exempt
29485     Exempt
29486     Exempt
29487     Exempt
29488     Exempt
29489     Exempt
29490     Exempt
29491     Exempt
29492     Exempt
29493     Exempt
29494     Exempt
29495     Exempt
29496     Exempt
29497     Exempt
29498     Exempt
29499     Exempt
29500     Exempt
29501     Exempt
29502     Exempt
29503     Exempt
29504     Exempt
29505     Exempt
29506     Exempt
29507     Exempt
29508     Exempt
29509     Exempt
29510     Exempt
29511     Exempt
29512     Exempt
29513     Exempt
29514     Exempt
29515     Exempt
29516     Exempt
29517     Exempt
29518     Exempt
29519     Exempt
29520     Exempt
29521     Exempt
29522     Exempt
29523     Exempt
50898     Exempt
50899     Exempt
50900     Exempt
50901     Exempt
50902     Exempt
50903     Exempt
50904     Exempt
50905     Exempt
50906     Exempt
50907     Exempt
50908     Exempt
50909     Exempt
50910     Exempt
50911     Exempt
50912     Exempt
50913     Exempt
50914     Exempt
50915     Exempt
50916     Exempt
50917     Exempt
50918     Exempt
50919     Exempt
50920     Exempt
50921     Exempt
50922     Exempt
50923     Exempt
50924     Exempt
50925     Exempt
50926     Exempt
50927     Exempt
50928     Exempt
50929     Exempt
50930     Exempt
50931     Exempt
50932     Exempt
50933     Exempt
50934     Exempt
50935     Exempt
50936     Exempt
50937     Exempt
50938     Exempt
50939     Exempt
50940     Exempt
50941     Exempt
50942     Exempt
50943     Exempt
50944     Exempt
50945     Exempt
50946     Exempt
50947     Exempt
50948     Exempt
50949     Exempt
50950     Exempt
50951     Exempt
50952     Exempt
50953     Exempt
50954     Exempt
50955     Exempt
50956     Exempt
50957     Exempt
52207     Exempt
52208     Exempt
52209     Exempt
52210     Exempt
52211     Exempt
52212     Exempt
52213     Exempt
52214     Exempt
52215     Exempt
52216     Exempt
52217     Exempt
52218     Exempt
52219     Exempt
53255     Exempt
53256     Exempt
53257     Exempt
54407     Exempt
54408     Exempt
54409     Exempt
54410     Exempt
54411     Exempt
54412     Exempt
54413     Exempt
54414     Exempt
54415     Exempt
54416     Exempt
54417     Exempt
54418     Exempt
54419     Exempt
54420     Exempt
54421     Exempt
54422     Exempt
54423     Exempt
54650     Exempt
54720     Exempt
54721     Exempt
54722     Exempt
54723     Exempt
54724     Exempt
54725     Exempt
54726     Exempt
54727     Exempt
54728     Exempt
54966     Exempt
83116     Exempt
87337     Exempt
87822     Exempt
95056     Exempt
95065     Exempt
96780     Exempt
96781     Exempt
96782     Exempt
96783     Exempt
96784     Exempt
96785     Exempt
96786     Exempt
96787     Exempt
97195     Exempt
97196     Exempt
97197     Exempt
97198     Exempt
97199     Exempt
97200     Exempt
98039     Exempt
98040     Exempt
98041     Exempt
98042     Exempt
98043     Exempt
98044     Exempt
98045     Exempt
98728     Exempt
98729     Exempt
98730     Exempt
98731     Exempt
98732     Exempt
98733     Exempt
98836     Exempt
98837     Exempt
98838     Exempt
98893     Exempt
98894     Exempt
98895     Exempt
98896     Exempt
99278     Exempt
99279     Exempt
99280     Exempt
115901    Exempt
115902    Exempt
115903    Exempt
115904    Exempt
115905    Exempt
115906    Exempt
115907    Exempt
115908    Exempt
115909    Exempt
115910    Exempt
115911    Exempt
115912    Exempt
115913    Exempt
115914    Exempt
115915    Exempt
115916    Exempt
115917    Exempt
115918    Exempt
115919    Exempt
115920    Exempt
115921    Exempt
115922    Exempt
115923    Exempt
115924    Exempt
115925    Exempt
115926    Exempt
115927    Exempt
115928    Exempt
115929    Exempt
115930    Exempt
115931    Exempt
115932    Exempt
115933    Exempt
115934    Exempt
115935    Exempt
115936    Exempt
115937    Exempt
115938    Exempt
115939    Exempt
115940    Exempt
115941    Exempt
115942    Exempt
115943    Exempt
115944    Exempt
115945    Exempt
115946    Exempt
115947    Exempt
115948    Exempt
115949    Exempt
115950    Exempt
115951    Exempt
115952    Exempt
115953    Exempt
115954    Exempt
115955    Exempt
115956    Exempt
115957    Exempt
115958    Exempt
115959    Exempt
115960    Exempt
115961    Exempt
115962    Exempt
115963    Exempt
115964    Exempt
115965    Exempt
115966    Exempt
115967    Exempt
115968    Exempt
115969    Exempt
115970    Exempt
115971    Exempt
115972    Exempt
115973    Exempt
115974    Exempt
115975    Exempt
115976    Exempt
115977    Exempt
115978    Exempt
115979    Exempt
117227    Exempt
117228    Exempt
117229    Exempt
117230    Exempt
117231    Exempt
118361    Exempt
125537    Exempt
125538    Exempt
125539    Exempt
125540    Exempt
125541    Exempt
125542    Exempt
125543    Exempt
125544    Exempt
125545    Exempt
125546    Exempt
125547    Exempt
125548    Exempt
125549    Exempt
125550    Exempt
125551    Exempt
125552    Exempt
125553    Exempt
125554    Exempt
125555    Exempt
125556    Exempt
125557    Exempt
125558    Exempt
125559    Exempt
125560    Exempt
125561    Exempt
125562    Exempt
125563    Exempt
125564    Exempt
125565    Exempt
125566    Exempt
125567    Exempt
125568    Exempt
125569    Exempt
125570    Exempt
125571    Exempt
125572    Exempt
125573    Exempt
125574    Exempt
125575    Exempt
125576    Exempt
125577    Exempt
125578    Exempt
127653    Exempt
127654    Exempt
127655    Exempt
127656    Exempt
127657    Exempt
127658    Exempt
128631    Exempt
129358    Exempt
129359    Exempt
129360    Exempt
129361    Exempt
129362    Exempt
129363    Exempt
129364    Exempt
129365    Exempt
129366    Exempt
141926    Exempt
141927    Exempt
141928    Exempt
141929    Exempt
141930    Exempt
141931    Exempt
141932    Exempt
141933    Exempt
141934    Exempt
141935    Exempt
141936    Exempt
141937    Exempt
141938    Exempt
141939    Exempt
141940    Exempt
141941    Exempt
141942    Exempt
141943    Exempt
141944    Exempt
141945    Exempt
141946    Exempt
141947    Exempt
141948    Exempt
141949    Exempt
141950    Exempt
141951    Exempt
141952    Exempt
141953    Exempt
141954    Exempt
143729    Exempt
143730    Exempt
143731    Exempt
143732    Exempt
143733    Exempt
143734    Exempt
143735    Exempt
143736    Exempt
143737    Exempt
143738    Exempt
143739    Exempt
143740    Exempt
143741    Exempt
143742    Exempt
143743    Exempt
143744    Exempt
143745    Exempt
143746    Exempt
143747    Exempt
143748    Exempt
143749    Exempt
143750    Exempt
143751    Exempt
143752    Exempt
143753    Exempt
143754    Exempt
143755    Exempt
143756    Exempt
143757    Exempt
143758    Exempt
143759    Exempt
143760    Exempt
143761    Exempt
143762    Exempt
143763    Exempt
143764    Exempt
143765    Exempt
143766    Exempt
143767    Exempt
143768    Exempt
143769    Exempt
143770    Exempt
143771    Exempt
143772    Exempt
143773    Exempt
143774    Exempt
143775    Exempt
143776    Exempt
143777    Exempt
143778    Exempt
143779    Exempt
143780    Exempt
143781    Exempt
143782    Exempt
143783    Exempt
143784    Exempt
143785    Exempt
143786    Exempt
143787    Exempt
143788    Exempt
143789    Exempt
143790    Exempt
143791    Exempt
143792    Exempt
143793    Exempt
143794    Exempt
143795    Exempt
143796    Exempt
143797    Exempt
143798    Exempt
143799    Exempt
143800    Exempt
143801    Exempt
143802    Exempt
143803    Exempt
143804    Exempt
143805    Exempt
143806    Exempt
143807    Exempt
143808    Exempt
143809    Exempt
143810    Exempt
143811    Exempt
143812    Exempt
143813    Exempt
143814    Exempt
143815    Exempt
143816    Exempt
143817    Exempt
143818    Exempt
143819    Exempt
143820    Exempt
143821    Exempt
143822    Exempt
143823    Exempt
143824    Exempt
143825    Exempt
143826    Exempt
143827    Exempt
143828    Exempt
143829    Exempt
143830    Exempt
143831    Exempt
143832    Exempt
143833    Exempt
143834    Exempt
143835    Exempt
143836    Exempt
143837    Exempt
143838    Exempt
143839    Exempt
143840    Exempt
143841    Exempt
143842    Exempt
143843    Exempt
143844    Exempt
144534    Exempt
145767    Exempt
145768    Exempt
145769    Exempt
145770    Exempt
145771    Exempt
145772    Exempt
145773    Exempt
145774    Exempt
145775    Exempt
145776    Exempt
145777    Exempt
145778    Exempt
145779    Exempt
145780    Exempt
145781    Exempt
145782    Exempt
145783    Exempt
145784    Exempt
145785    Exempt
145786    Exempt
145787    Exempt
145788    Exempt
145789    Exempt
145790    Exempt
145791    Exempt
145792    Exempt
145793    Exempt
145794    Exempt
145795    Exempt
145796    Exempt
145797    Exempt
145798    Exempt
145799    Exempt
145800    Exempt
145801    Exempt
145802    Exempt
145803    Exempt
145804    Exempt
145805    Exempt
145806    Exempt
145807    Exempt
145808    Exempt
145809    Exempt
145810    Exempt
145811    Exempt
145812    Exempt
145813    Exempt
145814    Exempt
145815    Exempt
145816    Exempt
145817    Exempt
145818    Exempt
145819    Exempt
145820    Exempt
145821    Exempt
145822    Exempt
145823    Exempt
145824    Exempt
145825    Exempt
145826    Exempt
145827    Exempt
145828    Exempt
145829    Exempt
145830    Exempt
145831    Exempt
145832    Exempt
145833    Exempt
145834    Exempt
145835    Exempt
145836    Exempt
148792    Exempt
148793    Exempt
148794    Exempt
148795    Exempt
148796    Exempt
148797    Exempt
148798    Exempt
148799    Exempt
148800    Exempt
148801    Exempt
148802    Exempt
148803    Exempt
148804    Exempt
148805    Exempt
148806    Exempt
148807    Exempt
148808    Exempt
148809    Exempt
148810    Exempt
148811    Exempt
148812    Exempt
148813    Exempt
148814    Exempt
148815    Exempt
148816    Exempt
148817    Exempt
148818    Exempt
148819    Exempt
148820    Exempt
148821    Exempt
148822    Exempt
148823    Exempt
148824    Exempt
148825    Exempt
148826    Exempt
148827    Exempt
148828    Exempt
148829    Exempt
148830    Exempt
148831    Exempt
148832    Exempt
148833    Exempt
148834    Exempt
148835    Exempt
148836    Exempt
148837    Exempt
148838    Exempt
148839    Exempt
148840    Exempt
148841    Exempt
148842    Exempt
148843    Exempt
148844    Exempt
148845    Exempt
148846    Exempt
148847    Exempt
148848    Exempt
148849    Exempt
148850    Exempt
148851    Exempt
148852    Exempt
148853    Exempt
148854    Exempt
148855    Exempt
148856    Exempt
148857    Exempt
148858    Exempt
148859    Exempt
148860    Exempt
148861    Exempt
148862    Exempt
148863    Exempt
148864    Exempt
148865    Exempt
148866    Exempt
148867    Exempt
148868    Exempt
148869    Exempt
148870    Exempt
148871    Exempt
148872    Exempt
148873    Exempt
148874    Exempt
148875    Exempt
148876    Exempt
148877    Exempt
148878    Exempt
148879    Exempt
148880    Exempt
148881    Exempt
148882    Exempt
148883    Exempt
148884    Exempt
148885    Exempt
148886    Exempt
148887    Exempt
148888    Exempt
148889    Exempt
148890    Exempt
148891    Exempt
148892    Exempt
148893    Exempt
148894    Exempt
148895    Exempt
148896    Exempt
148897    Exempt
148898    Exempt
148899    Exempt
148900    Exempt
148901    Exempt
148902    Exempt
148903    Exempt
148904    Exempt
148905    Exempt
148906    Exempt
148907    Exempt
148908    Exempt
148909    Exempt
148910    Exempt
148911    Exempt
148912    Exempt
148913    Exempt
148914    Exempt
148915    Exempt
148916    Exempt
148917    Exempt
148918    Exempt
148919    Exempt
148920    Exempt
148921    Exempt
148922    Exempt
148923    Exempt
148924    Exempt
148925    Exempt
148926    Exempt
148927    Exempt
148928    Exempt
148929    Exempt
148930    Exempt
148931    Exempt
148932    Exempt
148933    Exempt
148934    Exempt
148935    Exempt
148936    Exempt
148937    Exempt
148938    Exempt
148939    Exempt
148940    Exempt
148941    Exempt
148942    Exempt
148943    Exempt
148944    Exempt
148945    Exempt
148946    Exempt
148947    Exempt
148948    Exempt
148949    Exempt
148950    Exempt
148951    Exempt
148952    Exempt
148953    Exempt
148954    Exempt
148955    Exempt
148956    Exempt
148957    Exempt
148958    Exempt
148959    Exempt
148960    Exempt
148961    Exempt
148962    Exempt
148963    Exempt
148964    Exempt
148965    Exempt
148966    Exempt
148967    Exempt
148968    Exempt
148969    Exempt
148970    Exempt
148971    Exempt
148972    Exempt
148973    Exempt
148974    Exempt
148975    Exempt
148976    Exempt
148977    Exempt
148978    Exempt
148979    Exempt
148980    Exempt
148981    Exempt
148982    Exempt
148983    Exempt
148984    Exempt
148985    Exempt
148986    Exempt
148987    Exempt
148988    Exempt
148989    Exempt
148990    Exempt
148991    Exempt
148992    Exempt
148993    Exempt
148994    Exempt
148995    Exempt
148996    Exempt
148997    Exempt
148998    Exempt
148999    Exempt
149000    Exempt
149001    Exempt
149002    Exempt
149003    Exempt
149004    Exempt
149005    Exempt
149006    Exempt
149007    Exempt
149008    Exempt
149009    Exempt
149010    Exempt
149011    Exempt
149012    Exempt
149013    Exempt
149014    Exempt
149015    Exempt
149016    Exempt
149017    Exempt
149018    Exempt
149019    Exempt
149020    Exempt
149021    Exempt
149022    Exempt
149023    Exempt
149024    Exempt
149025    Exempt
149026    Exempt
149027    Exempt
149028    Exempt
149029    Exempt
149030    Exempt
149031    Exempt
149032    Exempt
149033    Exempt
149034    Exempt
149035    Exempt
149036    Exempt
149037    Exempt
149038    Exempt
149039    Exempt
149040    Exempt
149041    Exempt
149042    Exempt
149043    Exempt
149044    Exempt
149045    Exempt
149046    Exempt
149047    Exempt
149048    Exempt
149049    Exempt
149050    Exempt
149051    Exempt
149052    Exempt
149053    Exempt
149054    Exempt
149055    Exempt
149056    Exempt
149057    Exempt
149058    Exempt
149059    Exempt
149060    Exempt
149061    Exempt
149062    Exempt
149063    Exempt
149064    Exempt
149065    Exempt
149066    Exempt
149067    Exempt
149068    Exempt
149069    Exempt
149070    Exempt
149071    Exempt
149072    Exempt
149073    Exempt
149074    Exempt
149075    Exempt
149076    Exempt
149077    Exempt
149078    Exempt
149079    Exempt
149080    Exempt
149081    Exempt
149082    Exempt
149083    Exempt
149084    Exempt
149085    Exempt
149086    Exempt
149087    Exempt
149088    Exempt
149089    Exempt
149090    Exempt
149091    Exempt
149092    Exempt
149093    Exempt
149094    Exempt
149095    Exempt
149096    Exempt
149097    Exempt
149098    Exempt
149099    Exempt
149100    Exempt
149101    Exempt
149102    Exempt
149103    Exempt
149104    Exempt
149105    Exempt
149445    Exempt
149446    Exempt
149447    Exempt
149448    Exempt
149449    Exempt
149450    Exempt
149451    Exempt
149452    Exempt
149453    Exempt
149454    Exempt
149455    Exempt
149456    Exempt
149457    Exempt
149458    Exempt
149459    Exempt
149460    Exempt
149461    Exempt
149462    Exempt
149463    Exempt
149464    Exempt
149465    Exempt
149466    Exempt
149467    Exempt
149468    Exempt
149469    Exempt
149470    Exempt
149471    Exempt
149472    Exempt
149473    Exempt
149474    Exempt
149475    Exempt
149476    Exempt
149477    Exempt
153679    Exempt
153680    Exempt
153681    Exempt
153682    Exempt
153683    Exempt
153684    Exempt
153685    Exempt
153686    Exempt
153687    Exempt
153688    Exempt
153689    Exempt
153690    Exempt
153691    Exempt
153692    Exempt
154320    Exempt
156036    Exempt
156037    Exempt
163547    Exempt
163756    Exempt
166901    Exempt
166902    Exempt
166903    Exempt
167088    Exempt
167089    Exempt
167090    Exempt
167091    Exempt
167092    Exempt
167093    Exempt
167094    Exempt
167095    Exempt
167096    Exempt
167097    Exempt
167662    Exempt
167663    Exempt
167679    Exempt
168684    Exempt
168685    Exempt
168686    Exempt
168687    Exempt
168688    Exempt
168689    Exempt
168690    Exempt
168691    Exempt
168692    Exempt
168693    Exempt
168694    Exempt
168695    Exempt
168696    Exempt
168697    Exempt
168698    Exempt
168699    Exempt
168700    Exempt
168701    Exempt
168702    Exempt
168703    Exempt
168704    Exempt
168705    Exempt
168706    Exempt
169003    Exempt
169004    Exempt
169005    Exempt
169006    Exempt
169007    Exempt
169008    Exempt
169009    Exempt
169010    Exempt
169011    Exempt
169012    Exempt
169013    Exempt
169014    Exempt
169015    Exempt
169016    Exempt
169017    Exempt
169018    Exempt
169019    Exempt
169020    Exempt
169021    Exempt
169022    Exempt
169023    Exempt
169024    Exempt
169025    Exempt
169026    Exempt
169027    Exempt
169028    Exempt
169029    Exempt
169030    Exempt
169031    Exempt
169032    Exempt
169033    Exempt
169034    Exempt
169035    Exempt
169036    Exempt
169037    Exempt
169038    Exempt
169039    Exempt
169040    Exempt
169041    Exempt
169042    Exempt
169043    Exempt
169044    Exempt
169045    Exempt
169046    Exempt
169047    Exempt
169048    Exempt
169049    Exempt
169050    Exempt
169051    Exempt
169052    Exempt
169053    Exempt
169054    Exempt
169055    Exempt
169057    Exempt
169058    Exempt
169059    Exempt
169060    Exempt
169162    Exempt
169163    Exempt
169164    Exempt
169165    Exempt
169166    Exempt
169375    Exempt
169376    Exempt
169377    Exempt
169378    Exempt
169379    Exempt
169380    Exempt
191974    Exempt
191975    Exempt
191976    Exempt
192954    Exempt
203919    Exempt
203920    Exempt
203921    Exempt
203922    Exempt
203923    Exempt
203924    Exempt
203925    Exempt
203926    Exempt
203927    Exempt
203928    Exempt
203929    Exempt
203930    Exempt
203931    Exempt
203932    Exempt
203933    Exempt
203934    Exempt
203935    Exempt
203936    Exempt
203937    Exempt
203938    Exempt
203939    Exempt
203940    Exempt
203941    Exempt
203942    Exempt
203943    Exempt
203944    Exempt
204114    Exempt
204115    Exempt
204116    Exempt
204117    Exempt
204118    Exempt
204119    Exempt
204120    Exempt
204121    Exempt
Name: interest_rate, dtype: str

In [20]:
df["interest_rate_numeric"] = pd.to_numeric(df["interest_rate"], errors="coerce")
df["interest_rate_numeric"].mean()

np.float64(7.488759375059678)

In [21]:
df["income"].describe()

count    1.786490e+05
mean     5.545265e+02
std      6.898490e+04
min     -1.131200e+04
25%      1.010000e+02
50%      1.600000e+02
75%      2.600000e+02
max      2.555358e+07
Name: income, dtype: float64

In [22]:
df["debt_to_income_ratio"].value_counts(dropna=False)

debt_to_income_ratio
NaN         77676
50%-60%     14282
>60%        14188
30%-<36%    13980
20%-<30%    11335
49          10430
44           6466
<20%         6139
48           5868
42           5456
47           5168
43           4971
45           4694
46           4644
41           4574
40           4354
39           3913
38           3463
37           3169
36           2983
Exempt       1128
Name: count, dtype: int64

# Answering Sample questions with SQL

In [23]:
import duckdb

In [24]:
# "what is the average loan amount by loan type"

result = duckdb.query("""
    SELECT "loan_type", 
    ROUND(AVG("loan_amount"), 2) as avg_loan_amount
    FROM df
    GROUP BY "loan_type"
    ORDER BY avg_loan_amount DESC
""").to_df()

print(result)

   loan_type  avg_loan_amount
0          3        682024.63
1          1        601431.62
2          2        597897.07
3          4        233275.86

Future Queries: This average loan amount calculation currently includes all
records. Depending on the user's question, it may be important to distinguish
between approved loans and denied loans. Also, it may be relevant to include
the number of records contributing to the average for interpretibility.

In [25]:
# what were the main denial reasons?

result = duckdb.query("""
    SELECT "denial_reason-1", COUNT(*) AS num_denials
    FROM df
    WHERE "action_taken" = 3
    AND "denial_reason-1" != 1111 AND "denial_reason-1" !=10
    GROUP BY "denial_reason-1"
    ORDER BY "num_denials" DESC
""").to_df()

print(result)

   denial_reason-1  num_denials
0                1        15919
1                7         6123
2                3         5862
3                4         4986
4                9         3865
5                6         1652
6                5         1085
7                2          197
8                8            3

Denial Reasons: The query considers only denial_reason-1. It may be relevant
to consider all four denial reasons.

# Schema Formulation

In [26]:
import duckdb

schema = duckdb.sql("""
    DESCRIBE SELECT * FROM df
""").df()

schema[["column_name", "column_type"]]

                                 column_name column_type
0                              activity_year      BIGINT
1                                        lei     VARCHAR
2                             derived_msa-md      BIGINT
3                                 state_code     VARCHAR
4                                county_code      BIGINT
5                               census_tract      DOUBLE
6                      conforming_loan_limit     VARCHAR
7                  derived_loan_product_type     VARCHAR
8                  derived_dwelling_category     VARCHAR
9                          derived_ethnicity     VARCHAR
10                              derived_race     VARCHAR
11                               derived_sex     VARCHAR
12                              action_taken      BIGINT
13                            purchaser_type      BIGINT
14                               preapproval      BIGINT
15                                 loan_type      BIGINT
16                              loan_purpose      BIGINT
17                               lien_status      BIGINT
18                          reverse_mortgage      BIGINT
19                   open-end_line_of_credit      BIGINT
20            business_or_commercial_purpose      BIGINT
21                               loan_amount      DOUBLE
22                       loan_to_value_ratio     VARCHAR
23                             interest_rate     VARCHAR
24                               rate_spread     VARCHAR
25                              hoepa_status      BIGINT
26                          total_loan_costs     VARCHAR
27                     total_points_and_fees     VARCHAR
28                       origination_charges     VARCHAR
29                           discount_points     VARCHAR
30                            lender_credits     VARCHAR
31                                 loan_term     VARCHAR
32                   prepayment_penalty_term     VARCHAR
33                         intro_rate_period     VARCHAR
34                     negative_amortization      BIGINT
35                     interest_only_payment      BIGINT
36                           balloon_payment      BIGINT
37              other_nonamortizing_features      BIGINT
38                            property_value     VARCHAR
39                       construction_method      BIGINT
40                            occupancy_type      BIGINT
41   manufactured_home_secured_property_type      BIGINT
42  manufactured_home_land_property_interest      BIGINT
43                               total_units     VARCHAR
44              multifamily_affordable_units     VARCHAR
45                                    income      DOUBLE
46                      debt_to_income_ratio     VARCHAR
47               applicant_credit_score_type      BIGINT
48            co-applicant_credit_score_type      BIGINT
49                     applicant_ethnicity-1      DOUBLE
50                     applicant_ethnicity-2      DOUBLE
51                     applicant_ethnicity-3      DOUBLE
52                     applicant_ethnicity-4      DOUBLE
53                     applicant_ethnicity-5      DOUBLE
54                  co-applicant_ethnicity-1      DOUBLE
55                  co-applicant_ethnicity-2      DOUBLE
56                  co-applicant_ethnicity-3      DOUBLE
57                  co-applicant_ethnicity-4      DOUBLE
58                  co-applicant_ethnicity-5      DOUBLE
59              applicant_ethnicity_observed      BIGINT
60           co-applicant_ethnicity_observed      BIGINT
61                          applicant_race-1      DOUBLE
62                          applicant_race-2      DOUBLE
63                          applicant_race-3      DOUBLE
64                          applicant_race-4      DOUBLE
65                          applicant_race-5      DOUBLE
66                       co-applicant_race-1      DOUBLE
67                       co-applicant_race-2      DOUBLE
68                       co-applicant_race-3      DOUBLE
69                       co-applicant_race-4      DOUBLE
70                       co-applicant_race-5      DOUBLE
71                   applicant_race_observed      BIGINT
72                co-applicant_race_observed      BIGINT
73                             applicant_sex      BIGINT
74                          co-applicant_sex      BIGINT
75                    applicant_sex_observed      BIGINT
76                 co-applicant_sex_observed      BIGINT
77                             applicant_age     VARCHAR
78                          co-applicant_age     VARCHAR
79                    applicant_age_above_62     VARCHAR
80                 co-applicant_age_above_62     VARCHAR
81                 submission_of_application      BIGINT
82          initially_payable_to_institution      BIGINT
83                                     aus-1      BIGINT
84                                     aus-2      DOUBLE
85                                     aus-3      DOUBLE
86                                     aus-4      DOUBLE
87                                     aus-5      DOUBLE
88                           denial_reason-1      BIGINT
89                           denial_reason-2      DOUBLE
90                           denial_reason-3      DOUBLE
91                           denial_reason-4      DOUBLE
92                          tract_population      BIGINT
93         tract_minority_population_percent      DOUBLE
94         ffiec_msa_md_median_family_income      BIGINT
95            tract_to_msa_income_percentage      BIGINT
96                tract_owner_occupied_units      BIGINT
97            tract_one_to_four_family_homes      BIGINT
98         tract_median_age_of_housing_units      BIGINT
99                     interest_rate_numeric      DOUBLE